// --- APP STATE ---
const app = {
    state: {
        currentView: 'dashboard',
        settings: { name: '', weatherKey: '' },
        boqItems: []
    },

    init() {
        this.loadState();
        this.renderNav();
        this.renderMaterials();
        this.updateConvUnits(); // Init converter dropdowns
        takeoffApp.renderTable();
        lucide.createIcons();

        // Mobile menu toggle
        document.getElementById('mobile-menu-btn').addEventListener('click', () => {
            const sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('-translate-x-full');
        });

        // Init Sketchpad
        sketchApp.init();
    },

    loadState() {
        const saved = localStorage.getItem('sitecalc_state');
        if (saved) {
            const parsed = JSON.parse(saved);
            this.state.settings = parsed.settings || { name: '', weatherKey: '', client: '', project: '' };
            this.state.boqItems = parsed.boqItems || [];

            document.getElementById('setting-name').value = this.state.settings.name || '';
            document.getElementById('setting-client').value = this.state.settings.client || '';
            document.getElementById('setting-project').value = this.state.settings.project || '';
            document.getElementById('setting-weather-key').value = this.state.settings.weatherKey || '';
        }
    },

    saveSettings() {
        this.state.settings.name = document.getElementById('setting-name').value;
        this.state.settings.client = document.getElementById('setting-client').value;
        this.state.settings.project = document.getElementById('setting-project').value;
        this.state.settings.weatherKey = document.getElementById('setting-weather-key').value;
        this.saveState();
        alert('Settings Saved');
    },

    // ... (rest of the file) ...

    // --- REPORTING ---
    exportReport() {
        if (!window.jspdf) {
            alert('PDF Library not loaded. Please check internet connection.');
            return;
        }
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        let y = 20;

        // --- HEADER ---
        doc.setFillColor(30, 58, 138); // Civil-800
        doc.rect(0, 0, 210, 30, 'F');
        doc.setTextColor(255, 255, 255);

        doc.setFontSize(22);
        doc.text("Project Report", 14, 18);

        doc.setFontSize(10);
        doc.text("Generated by SiteCalc", 14, 25);
        doc.text(new Date().toDateString(), 196, 18, { align: 'right' });

        y = 45;

        // --- PROJECT INFO ---
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.text("Project Details", 14, y);
        y += 8;
        doc.setFont(undefined, 'normal');
        doc.setFontSize(10);

        const details = [
            `Engineer: ${this.state.settings.name || 'N/A'}`,
            `Client: ${this.state.settings.client || 'N/A'}`,
            `Project: ${this.state.settings.project || 'N/A'}`
        ];

        details.forEach(line => {
            doc.text(line, 14, y);
            y += 6;
        });
        y += 10;

        // --- SITE DATA ---
        const geoText = document.getElementById('geo-result').innerText;
        // Clean up weather text to remove "Demo Mode" or buttons
        const wDisplay = document.getElementById('weather-display').innerText.replace('Set API Key', '').replace('Demo Mode', '').trim();

        if (!geoText.includes("not fetched") || wDisplay.length > 50) {
            doc.setFontSize(12);
            doc.setFont(undefined, 'bold');
            doc.text("Site Conditions", 14, y);
            y += 8;
            doc.setFont(undefined, 'normal');
            doc.setFontSize(10);

            const siteInfo = doc.splitTextToSize(`Geolocation:\n${geoText}\n\nWeather Snapshot:\n${wDisplay}`, 180);
            doc.text(siteInfo, 14, y);
            y += (siteInfo.length * 6) + 10;
        }

        // --- CALCULATIONS ---
        // Helper to check if calc has data (naive check against placeholder text)
        const getResult = (id, placeholder) => {
            const el = document.getElementById(id);
            if (!el || el.innerText.includes(placeholder)) return null;
            return el.innerText;
        };

        const calcs = [
            { title: "Concrete Mix Design", data: getResult('mix-results', 'Enter volume') },
            { title: "Slope & Gradient", data: getResult('slope-results', 'Enter Rise') },
            { title: "Beam Analysis", data: getResult('beam-results', 'Enter values') },
            { title: "Column Capacity", data: getResult('col-results', 'Enter parameters') }
        ];

        const activeCalcs = calcs.filter(c => c.data !== null);

        if (activeCalcs.length > 0) {
            if (y > 250) { doc.addPage(); y = 20; }
            doc.setFontSize(12);
            doc.setFont(undefined, 'bold');
            doc.text("Design Calculations", 14, y);
            y += 10;
            doc.setFont(undefined, 'normal');
            doc.setFontSize(10);

            activeCalcs.forEach(c => {
                if (y > 270) { doc.addPage(); y = 20; }

                doc.setFont(undefined, 'bold');
                doc.text(`> ${c.title}`, 14, y);
                y += 6;
                doc.setFont(undefined, 'normal');

                const lines = doc.splitTextToSize(c.data, 180);
                doc.text(lines, 14, y);
                y += (lines.length * 5) + 8;
            });
        }

        // --- BOQ ---
        if (this.state.boqItems.length > 0) {
            if (y > 250) { doc.addPage(); y = 20; }
            doc.setFontSize(12);
            doc.setFont(undefined, 'bold');
            doc.text("Bill of Quantities", 14, y);
            y += 5;

            const rows = this.state.boqItems.map((item, index) => [
                index + 1, item.desc, item.unit, item.qty, item.rate, (item.qty * item.rate).toFixed(2)
            ]);

            doc.autoTable({
                startY: y,
                head: [['#', 'Description', 'Unit', 'Qty', 'Rate', 'Amount']],
                body: rows,
                foot: [['', '', '', '', 'Total', document.getElementById('boq-total').innerText]],
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246] },
                margin: { left: 14 }
            });
            y = doc.lastAutoTable.finalY + 15;
        }

        doc.save('SiteCalc_Project_Report.pdf');
    },

    clearData() {
        if (confirm("Delete all saved data?")) {
            localStorage.removeItem('sitecalc_state');
            location.reload();
        }
    },

    // --- NAVIGATION ---
    routes: [
        { id: 'dashboard', icon: 'layout-dashboard', label: 'Dashboard' },
        { id: 'calculators', icon: 'calculator', label: 'Calculators' },
        { id: 'sketch', icon: 'pen-tool', label: 'Sketch & Measure' },
        { id: 'takeoff', icon: 'clipboard-list', label: 'Quantity Takeoff' },
        { id: 'materials', icon: 'library', label: 'Materials DB' },
        { id: 'site', icon: 'map', label: 'Site Tools' },
        { id: 'settings', icon: 'settings', label: 'Settings' }
    ],

    renderNav() {
        const ul = document.getElementById('nav-links');
        ul.innerHTML = this.routes.map(r => `
                    <li>
                        <button onclick="app.navigate('${r.id}')" 
                            class="nav-item w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${this.state.currentView === r.id ? 'bg-civil-600 text-white' : 'hover:bg-civil-800 text-slate-300'}">
                            <i data-lucide="${r.icon}" class="w-5 h-5"></i>
                            <span class="font-medium">${r.label}</span>
                        </button>
                    </li>
                `).join('');
        lucide.createIcons();
    },

    navigate(viewId) {
        this.state.currentView = viewId;

        // Update UI Sections
        document.querySelectorAll('.view-section').forEach(el => el.classList.add('hidden'));
        document.getElementById(`view-${viewId}`).classList.remove('hidden');

        // Update Sidebar
        this.renderNav();

        // Close sidebar on mobile after click
        if (window.innerWidth < 768) {
            document.getElementById('sidebar').classList.add('-translate-x-full');
        }

        // Title Update
        const route = this.routes.find(r => r.id === viewId);
        document.getElementById('page-title').innerHTML = `
                    <i data-lucide="${route.icon}" class="w-6 h-6 text-civil-600"></i> ${route.label}
                `;
        lucide.createIcons();

        // Specific view logic
        if (viewId === 'sketch') sketchApp.resize();
    },

    toggleHelp() {
        const el = document.getElementById('help-modal');
        el.classList.toggle('hidden');
    },
    toggleSettings() { this.navigate('settings'); },

    // --- CALCULATOR LOGIC ---
    switchCalc(type) {
        document.querySelectorAll('.calc-content').forEach(el => el.classList.add('hidden'));
        document.getElementById(`calc-${type}`).classList.remove('hidden');

        document.querySelectorAll('.calc-tab').forEach(el => {
            el.classList.remove('border-civil-600', 'text-civil-600');
            el.classList.add('border-transparent', 'text-slate-500');
        });
        event.target.classList.remove('border-transparent', 'text-slate-500');
        event.target.classList.add('border-civil-600', 'text-civil-600');
    },

    calculateBeam() {
        const L = parseFloat(document.getElementById('beam-L').value);
        const P = parseFloat(document.getElementById('beam-P').value);
        const a = parseFloat(document.getElementById('beam-a').value);

        if (!L || !P || isNaN(a)) return;

        const b = L - a;
        const R1 = (P * b) / L;
        const R2 = (P * a) / L;
        const maxM = (P * a * b) / L; // At load point

        document.getElementById('beam-results').innerHTML = `
                    <div class="grid grid-cols-2 gap-2 mt-2">
                        <div class="bg-white p-2 border rounded"><strong>R1 (Left):</strong> ${R1.toFixed(2)} kN</div>
                        <div class="bg-white p-2 border rounded"><strong>R2 (Right):</strong> ${R2.toFixed(2)} kN</div>
                        <div class="bg-white p-2 border rounded col-span-2"><strong>Max Moment (M):</strong> ${maxM.toFixed(2)} kNm</div>
                        <div class="text-xs text-slate-500 col-span-2 mt-1">Location of Max Moment: ${a}m from left support.</div>
                    </div>
                `;
    },

    calculateColumn() {
        const b = parseFloat(document.getElementById('col-b').value);
        const D = parseFloat(document.getElementById('col-d').value);
        const fck = parseFloat(document.getElementById('col-fck').value);
        const fy = parseFloat(document.getElementById('col-fy').value);
        const Asc = parseFloat(document.getElementById('col-asc').value);

        if (!b || !D) return;

        const Ag = b * D;
        const Ac = Ag - Asc;

        // IS 456 Simplified Formula for Axial Short Column
        // Pu = 0.4 fck Ac + 0.67 fy Asc
        const Pu_N = (0.4 * fck * Ac) + (0.67 * fy * Asc);
        const Pu_kN = Pu_N / 1000;

        document.getElementById('col-results').innerHTML = `
                    <div class="bg-white p-3 border rounded border-l-4 border-l-civil-500">
                        <div class="text-2xl font-bold text-civil-700">${Pu_kN.toFixed(1)} kN</div>
                        <div class="text-xs text-slate-500 mt-1">
                            Factored Axial Capacity<br>
                            Assuming min eccentricity requirements met.
                        </div>
                    </div>
                `;
    },

    updateConvUnits() {
        const cat = document.getElementById('conv-cat').value;
        const units = Object.keys(CONV_FACTORS[cat]);

        const createOptions = () => units.map(u => `<option value="${u}">${u}</option>`).join('');

        document.getElementById('conv-from').innerHTML = createOptions();
        document.getElementById('conv-to').innerHTML = createOptions();
        // Select second option for 'to' if available
        if (units.length > 1) document.getElementById('conv-to').selectedIndex = 1;

        this.convert();
    },

    convert() {
        const cat = document.getElementById('conv-cat').value;
        const val = parseFloat(document.getElementById('conv-val').value);
        const uFrom = document.getElementById('conv-from').value;
        const uTo = document.getElementById('conv-to').value;

        const factorFrom = CONV_FACTORS[cat][uFrom];
        const factorTo = CONV_FACTORS[cat][uTo];

        // Convert to base unit then to target
        const base = val * factorFrom;
        const result = base / factorTo;

        document.getElementById('conv-result').innerText = result.toLocaleString(undefined, { maximumFractionDigits: 6 }) + " " + uTo;
    },

    calculateMix() {
        const grade = document.getElementById('mix-grade').value;
        const vol = parseFloat(document.getElementById('mix-vol').value);

        if (!vol || vol <= 0) return;

        const ratio = MIX_RATIOS[grade];
        const totalParts = ratio.c + ratio.s + ratio.a;

        // Dry Volume Factor 1.54
        const dryVol = vol * 1.54;

        const cVol = (ratio.c / totalParts) * dryVol;
        const sVol = (ratio.s / totalParts) * dryVol;
        const aVol = (ratio.a / totalParts) * dryVol;

        // Density: Cement 1440, Sand 1600, Agg 1500 (Approx)
        const cKg = cVol * 1440;
        const sKg = sVol * 1600;
        const aKg = aVol * 1500;
        const bags = cKg / 50;

        document.getElementById('mix-results').innerHTML = `
            <div class="grid grid-cols-2 gap-2 text-sm">
                <div class="bg-slate-50 p-2 rounded"><strong>Ratio:</strong> 1 : ${ratio.s} : ${ratio.a}</div>
                <div class="bg-slate-50 p-2 rounded"><strong>Cement:</strong> ${bags.toFixed(1)} Bags</div>
                <div class="bg-slate-50 p-2 rounded"><strong>Sand:</strong> ${sKg.toFixed(0)} kg</div>
                <div class="bg-slate-50 p-2 rounded"><strong>Aggregate:</strong> ${aKg.toFixed(0)} kg</div>
            </div>
        `;
    },

    calculateSlope() {
        const rise = parseFloat(document.getElementById('slope-rise').value);
        const run = parseFloat(document.getElementById('slope-run').value);

        if (!rise || !run) return;

        const gradient = rise / run;
        const angleRad = Math.atan(gradient);
        const angleDeg = angleRad * (180 / Math.PI);
        const percent = gradient * 100;

        document.getElementById('slope-results').innerHTML = `
            <div class="flex flex-col gap-2 text-center">
                <div class="bg-civil-50 p-3 rounded-lg">
                    <div class="text-2xl font-bold text-civil-700">${angleDeg.toFixed(2)}°</div>
                    <div class="text-xs text-slate-500">Angle of Inclination</div>
                </div>
                <div class="bg-civil-50 p-3 rounded-lg">
                    <div class="text-2xl font-bold text-civil-700">${percent.toFixed(2)}%</div>
                    <div class="text-xs text-slate-500">Slope Percentage</div>
                </div>
            </div>
        `;
    },

    // --- MATERIALS LOGIC ---
    renderMaterials() {
        const container = document.getElementById('material-list');
        const query = document.getElementById('mat-search').value.toLowerCase();

        const filtered = MATERIALS_DB.filter(m => m.name.toLowerCase().includes(query) || m.cat.toLowerCase().includes(query));

        container.innerHTML = filtered.map(m => `
                    <div class="bg-white p-4 rounded-lg border border-slate-200 hover:shadow-md transition flex flex-col justify-between">
                        <div>
                            <div class="flex justify-between items-start">
                                <h4 class="font-bold text-civil-800">${m.name}</h4>
                                <span class="bg-slate-100 text-slate-600 text-[10px] px-2 py-0.5 rounded-full uppercase font-bold tracking-wider">${m.cat}</span>
                            </div>
                            <div class="mt-3 text-sm space-y-1 text-slate-600">
                                <div class="flex justify-between"><span>Density:</span> <span class="font-mono">${m.density} kg/m³</span></div>
                                <div class="flex justify-between"><span>Strength:</span> <span class="font-mono">${m.strength}</span></div>
                                <div class="flex justify-between"><span>E-Modulus:</span> <span class="font-mono">${m.mod}</span></div>
                            </div>
                        </div>
                    </div>
                `).join('');

        if (filtered.length === 0) container.innerHTML = `<div class="col-span-2 text-center text-slate-400 py-8">No materials found.</div>`;
    },

    filterMaterials() { this.renderMaterials(); },

    // --- SITE TOOLS ---
    getGeolocation() {
        const resDiv = document.getElementById('geo-result');
        resDiv.innerText = "Locating...";

        if (!navigator.geolocation) {
            resDiv.innerText = "Geolocation not supported.";
            return;
        }

        navigator.geolocation.getCurrentPosition(
            (pos) => {
                const { latitude, longitude, accuracy } = pos.coords;
                resDiv.innerHTML = `
                            Lat: ${latitude.toFixed(5)}<br>
                            Lon: ${longitude.toFixed(5)}<br>
                            Accuracy: ±${accuracy.toFixed(0)}m
                        `;

                // Fetch real weather if key exists
                if (this.state.settings.weatherKey) {
                    this.fetchWeather(latitude, longitude);
                } else {
                    // Mock Weather update if in demo mode
                    document.getElementById('weather-display').innerHTML += `
                                <div class="text-xs text-green-600 mt-2 font-bold">Coordinates Updated (Demo Mode)</div>
                            `;
                }
            },
            (err) => {
                resDiv.innerText = "Error: " + err.message;
            }
        );
    },

    async fetchWeather(lat, lon) {
        const apiKey = this.state.settings.weatherKey;
        const url = `https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=${apiKey}&units=metric`;

        const display = document.getElementById('weather-display');
        display.innerHTML = `<div class="text-center py-6 text-civil-600">Fetching live data...</div>`;

        try {
            const res = await fetch(url);
            if (!res.ok) throw new Error('Weather API Error');
            const data = await res.json();

            const temp = Math.round(data.main.temp);
            const desc = data.weather[0].main;
            const wind = (data.wind.speed * 3.6).toFixed(1); // m/s to km/h
            const humid = data.main.humidity;

            display.innerHTML = `
                <div class="text-center py-6">
                    <div
                        class="inline-block bg-green-50 text-green-800 px-3 py-1 rounded text-xs border border-green-200 mb-4">
                        Live Data Active</div>
                    <div class="flex justify-center items-center gap-4">
                        <div class="text-left">
                            <div class="text-3xl font-bold text-slate-800">${temp}°C</div>
                            <div class="text-sm text-slate-500">${desc}</div>
                        </div>
                        <div class="text-left text-xs text-slate-500 border-l pl-4">
                            <div>Wind: ${wind} km/h</div>
                            <div>Humidity: ${humid}%</div>
                        </div>
                    </div>
                    <div class="text-xs text-slate-400 mt-4">Source: OpenWeatherMap</div>
                </div>
            `;

        } catch (err) {
            console.error(err);
            display.innerHTML = `
                <div class="text-center py-6">
                    <div class="text-red-500 font-bold mb-2">Weather Fetch Failed</div>
                    <p class="text-xs text-slate-500">Check API Key in Settings.</p>
                    <div class="mt-4 text-xs text-slate-400">Reverted to Demo View</div>
                </div>
            `;
        }
    },

    // --- REPORTING ---

};

// --- SKETCH APP ---
const sketchApp = {
    canvas: null,
    ctx: null,
    mode: 'line', // line, measure
    isDrawing: false,
    scale: 0.05, // meters per pixel
    shapes: [], // {type: 'line', x1, y1, x2, y2, length}
    startPos: { x: 0, y: 0 },

    init() {
        this.canvas = document.getElementById('sketch-canvas');
        this.ctx = this.canvas.getContext('2d');
        this.resize();

        window.addEventListener('resize', () => this.resize());

        // Events
        this.canvas.addEventListener('mousedown', e => this.start(e));
        this.canvas.addEventListener('mousemove', e => this.draw(e));
        this.canvas.addEventListener('mouseup', e => this.end(e));
        this.canvas.addEventListener('touchstart', e => {
            const touch = e.touches[0];
            const mouseEvent = new MouseEvent('mousedown', {
                clientX: touch.clientX, clientY: touch.clientY
            });
            this.canvas.dispatchEvent(mouseEvent);
        }, { passive: false });
    },

    resize() {
        const parent = document.getElementById('canvas-container');
        if (parent) {
            this.canvas.width = parent.clientWidth;
            this.canvas.height = parent.clientHeight || 500;
            this.redraw();
        }
    },

    setMode(m) {
        this.mode = m;
        // UI Toggle
    },

    updateScale() {
        this.scale = parseFloat(document.getElementById('sketch-scale').value) || 0.05;
        this.redraw();
    },

    getPos(e) {
        const rect = this.canvas.getBoundingClientRect();
        return {
            x: e.clientX - rect.left,
            y: e.clientY - rect.top
        };
    },

    start(e) {
        this.isDrawing = true;
        this.startPos = this.getPos(e);
    },

    draw(e) {
        if (!this.isDrawing) return;
        const pos = this.getPos(e);
        this.redraw();

        // Draw Preview Line
        this.ctx.beginPath();
        this.ctx.strokeStyle = '#3b82f6';
        this.ctx.lineWidth = 2;
        this.ctx.moveTo(this.startPos.x, this.startPos.y);
        this.ctx.lineTo(pos.x, pos.y);
        this.ctx.stroke();

        // Live dimension
        const distPx = Math.hypot(pos.x - this.startPos.x, pos.y - this.startPos.y);
        const distM = (distPx * this.scale).toFixed(2);
        this.ctx.fillStyle = '#1e3a8a';
        this.ctx.font = '12px sans-serif';
        this.ctx.fillText(`${distM}m`, (this.startPos.x + pos.x) / 2, (this.startPos.y + pos.y) / 2 - 10);
    },

    end(e) {
        if (!this.isDrawing) return;
        this.isDrawing = false;
        const pos = this.getPos(e);

        // Save Shape
        const distPx = Math.hypot(pos.x - this.startPos.x, pos.y - this.startPos.y);
        if (distPx > 5) { // Ignore tiny clicks
            this.shapes.push({
                type: 'line',
                x1: this.startPos.x, y1: this.startPos.y,
                x2: pos.x, y2: pos.y,
                lengthPx: distPx
            });
            this.updateStats();
        }
        this.redraw();
    },

    redraw() {
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);

        // Grid
        this.ctx.strokeStyle = '#e2e8f0';
        this.ctx.lineWidth = 1;
        this.ctx.beginPath();
        for (let x = 0; x < this.canvas.width; x += 40) { this.ctx.moveTo(x, 0); this.ctx.lineTo(x, this.canvas.height); }
        for (let y = 0; y < this.canvas.height; y += 40) { this.ctx.moveTo(0, y); this.ctx.lineTo(this.canvas.width, y); }
        this.ctx.stroke();

        // Shapes
        this.shapes.forEach(s => {
            this.ctx.beginPath();
            this.ctx.strokeStyle = '#1e293b';
            this.ctx.lineWidth = 2;
            this.ctx.moveTo(s.x1, s.y1);
            this.ctx.lineTo(s.x2, s.y2);
            this.ctx.stroke();

            // Label
            const distM = (s.lengthPx * this.scale).toFixed(2);
            this.ctx.fillStyle = '#64748b';
            this.ctx.fillText(`${distM}m`, (s.x1 + s.x2) / 2, (s.y1 + s.y2) / 2 - 5);
        });
    },

    updateStats() {
        const totalPx = this.shapes.reduce((sum, s) => sum + s.lengthPx, 0);
        const totalM = (totalPx * this.scale).toFixed(2);
        document.getElementById('sketch-stats').innerText = `Items: ${this.shapes.length} | Total Length: ${totalM}m`;
    },

    clearCanvas() {
        this.shapes = [];
        this.redraw();
        this.updateStats();
    }
};

// --- TAKEOFF APP ---
const takeoffApp = {
    addItem() {
        app.state.boqItems.push({ desc: 'New Item', unit: 'm3', qty: 0, rate: 0 });
        this.renderTable();
        app.saveState();
    },

    removeItem(idx) {
        app.state.boqItems.splice(idx, 1);
        this.renderTable();
        app.saveState();
    },

    updateItem(idx, field, value) {
        app.state.boqItems[idx][field] = field === 'desc' || field === 'unit' ? value : parseFloat(value);
        this.renderTable();
        app.saveState();
    },

    renderTable() {
        const tbody = document.getElementById('boq-body');
        let total = 0;

        tbody.innerHTML = app.state.boqItems.map((item, i) => {
            const amount = item.qty * item.rate;
            total += amount;
            return `
                        <tr>
                            <td class="p-3 text-slate-500">${i + 1}</td>
                            <td class="p-3"><input type="text" value="${item.desc}" onchange="takeoffApp.updateItem(${i}, 'desc', this.value)" class="w-full bg-transparent border-b border-transparent hover:border-slate-300 focus:border-civil-500 outline-none"></td>
                            <td class="p-3"><input type="text" value="${item.unit}" onchange="takeoffApp.updateItem(${i}, 'unit', this.value)" class="w-20 bg-transparent border-b border-transparent hover:border-slate-300 focus:border-civil-500 outline-none"></td>
                            <td class="p-3"><input type="number" value="${item.qty}" onchange="takeoffApp.updateItem(${i}, 'qty', this.value)" class="w-20 bg-transparent border-b border-transparent hover:border-slate-300 focus:border-civil-500 outline-none"></td>
                            <td class="p-3"><input type="number" value="${item.rate}" onchange="takeoffApp.updateItem(${i}, 'rate', this.value)" class="w-24 bg-transparent border-b border-transparent hover:border-slate-300 focus:border-civil-500 outline-none"></td>
                            <td class="p-3 text-right font-mono">${amount.toFixed(2)}</td>
                            <td class="p-3"><button onclick="takeoffApp.removeItem(${i})" class="text-slate-400 hover:text-red-500"><i data-lucide="trash" class="w-4 h-4"></i></button></td>
                        </tr>
                    `;
        }).join('');

        document.getElementById('boq-total').innerText = total.toFixed(2);
        lucide.createIcons();
    }
};

// Initialize
window.onload = () => app.init();
